# Generated by Django 3.0.5 on 2020-05-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Again_Reg_No', models.CharField(default=False, max_length=100)),
                ('option1', models.BooleanField(default=False)),
                ('option2', models.BooleanField(default=False)),
                ('option3', models.BooleanField(default=False)),
                ('option4', models.BooleanField(default=False)),
            ],
        ),
    ]
