# Generated by Django 3.0.5 on 2020-04-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='phone',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
